import { createTheme } from '@uiw/codemirror-themes';
import { tags as t } from '@lezer/highlight';

const monokai = createTheme({
  theme: 'monokai',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#F8F8F2',
    caret: '#F92672',
    selection: '#49483E',
    selectionMatch: '#49483E',
    lineHighlight: 'rgba(73, 72, 62, 0.7)',
    gutterBorder: '1px solid #272822',
    gutterBackground: '#272822',
    gutterForeground: '#75715E',
  },
  styles: [
    { tag: t.comment, color: '#75715E' },
    { tag: t.variableName, color: '#F92672' },
    { tag: [t.string, t.special(t.brace)], color: '#E6DB74' },
    { tag: t.number, color: '#AE81FF' },
    { tag: t.bool, color: '#A6E22E' },
    { tag: t.null, color: '#A6E22E' },
    { tag: t.keyword, color: '#F92672' },
    { tag: t.operator, color: '#F92672' },
    { tag: t.className, color: '#A6E22E' },
    { tag: t.definition(t.typeName), color: '#A6E22E' },
    { tag: t.typeName, color: '#A6E22E' },
  ],
});

const dracula = createTheme({
  theme: 'dracula',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#F8F8F2',
    caret: '#FF79C6',
    selection: '#44475A',
    selectionMatch: '#44475A',
    lineHighlight: 'rgba(68, 71, 90, 0.7)',
    gutterBorder: '1px solid #282A36',
    gutterBackground: '#282A36',
    gutterForeground: '#6272A4',
  },
  styles: [
    { tag: t.comment, color: '#6272A4' },
    { tag: t.variableName, color: '#BD93F9' },
    { tag: [t.string, t.special(t.brace)], color: '#F1FA8C' },
    { tag: t.number, color: '#8BE9FD' },
    { tag: t.bool, color: '#FF79C6' },
    { tag: t.null, color: '#FF79C6' },
    { tag: t.keyword, color: '#FF79C6' },
    { tag: t.operator, color: '#FF79C6' },
    { tag: t.className, color: '#50FA7B' },
    { tag: t.definition(t.typeName), color: '#50FA7B' },
    { tag: t.typeName, color: '#50FA7B' },
  ],
});

const blueMoon = createTheme({
  theme: 'blueMoon',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#F8F8F2',
    caret: '#82AAFF',
    selection: '#44475A',
    selectionMatch: '#44475A',
    lineHighlight: 'rgba(68, 71, 90, 0.7)',
    gutterBorder: '1px solid #282A36',
    gutterBackground: '#282A36',
    gutterForeground: '#6272A4',
  },
  styles: [
    { tag: t.comment, color: '#6272A4' },
    { tag: t.variableName, color: '#82AAFF' },
    { tag: [t.string, t.special(t.brace)], color: '#F1FA8C' },
    { tag: t.number, color: '#8BE9FD' },
    { tag: t.bool, color: '#FF79C6' },
    { tag: t.null, color: '#FF79C6' },
    { tag: t.keyword, color: '#FF79C6' },
    { tag: t.operator, color: '#FF79C6' },
    { tag: t.className, color: '#50FA7B' },
    { tag: t.definition(t.typeName), color: '#50FA7B' },
    { tag: t.typeName, color: '#50FA7B' },
  ],
});

const sunset = createTheme({
  theme: 'sunset',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#F8F8F2',
    caret: '#FF4500',
    selection: '#44475A',
    selectionMatch: '#44475A',
    lineHighlight: 'rgba(68, 71, 90, 0.7)',
    gutterBorder: '1px solid #282A36',
    gutterBackground: '#282A36',
    gutterForeground: '#6272A4',
  },
  styles: [
    { tag: t.comment, color: '#6272A4' },
    { tag: t.variableName, color: '#FF4500' },
    { tag: [t.string, t.special(t.brace)], color: '#F1FA8C' },
    { tag: t.number, color: '#8BE9FD' },
    { tag: t.bool, color: '#FF79C6' },
    { tag: t.null, color: '#FF79C6' },
    { tag: t.keyword, color: '#FF79C6' },
    { tag: t.operator, color: '#FF79C6' },
    { tag: t.className, color: '#50FA7B' },
    { tag: t.definition(t.typeName), color: '#50FA7B' },
    { tag: t.typeName, color: '#50FA7B' },
  ],
});

const greenForest = createTheme({
  theme: 'greenForest',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#F8F8F2',
    caret: '#50FA7B',
    selection: '#44475A',
    selectionMatch: '#44475A',
    lineHighlight: 'rgba(68, 71, 90, 0.7)',
    gutterBorder: '1px solid #282A36',
    gutterBackground: '#282A36',
    gutterForeground: '#6272A4',
  },
  styles: [
    { tag: t.comment, color: '#6272A4' },
    { tag: t.variableName, color: '#50FA7B' },
    { tag: [t.string, t.special(t.brace)], color: '#F1FA8C' },
    { tag: t.number, color: '#8BE9FD' },
    { tag: t.bool, color: '#FF79C6' },
    { tag: t.null, color: '#FF79C6' },
    { tag: t.keyword, color: '#FF79C6' },
    { tag: t.operator, color: '#FF79C6' },
    { tag: t.className, color: '#50FA7B' },
    { tag: t.definition(t.typeName), color: '#50FA7B' },
    { tag: t.typeName, color: '#50FA7B' },
  ],
});


const ayuDark = createTheme({
  theme: 'ayuDark',
  settings: {
    background: 'transparent',
    backgroundImage: '',
    foreground: '#B3B1AD',
    caret: '#FFCC66',
    selection: '#253340',
    selectionMatch: '#253340',
    lineHighlight: 'rgba(37, 52, 64, 0.7)',
    gutterBorder: '1px solid #0A0E14',
    gutterBackground: '#0A0E14',
    gutterForeground: '#4E5561',
  },
  styles: [
    { tag: t.comment, color: '#4E5561' },
    { tag: t.variableName, color: '#FFCC66' },
    { tag: [t.string, t.special(t.brace)], color: '#BAE67E' },
    { tag: t.number, color: '#D4BFFF' },
    { tag: t.bool, color: '#FF8F40' },
    { tag: t.null, color: '#FF8F40' },
    { tag: t.keyword, color: '#FF8F40' },
    { tag: t.operator, color: '#FF8F40' },
    { tag: t.className, color: '#5CCFE6' },
    { tag: t.definition(t.typeName), color: '#5CCFE6' },
    { tag: t.typeName, color: '#5CCFE6' },
  ],
});

export const themes: Themes = {
  "dracula": dracula,
  "monokai": monokai,
  "blueMoon": blueMoon,
  "greenForest": greenForest,
  "ayuDark": ayuDark,
}